import JSZip from 'jszip';
import Epub from 'epub-gen-memory';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import MarkdownIt from 'markdown-it';
import { Project, Chapter } from '../types';

const md = new MarkdownIt();

export async function exportToZip(project: Project, chapters: Chapter[], language: string, publishOptions: any = {}) {
  const zip = new JSZip();
  const metaFolder = zip.folder("metadata");
  const contentFolder = zip.folder("chapters");
  
  const metadata = {
    title: project.title,
    niche: project.niche,
    tone: project.tone,
    writingStyle: project.writingStyle,
    audience: project.audience,
    language: language,
    exportedAt: new Date().toISOString()
  };
  metaFolder?.file("ebook_metadata.json", JSON.stringify(metadata, null, 2));

  await Promise.all(chapters.map(async (ch, index) => {
    const url = language === 'en' ? ch.contentUrl : ch.translations?.[language]?.contentUrl;
    if (!url) return;
    
    const response = await fetch(url);
    if (!response.ok) return;
    const text = await response.text();
    
    const title = language === 'en' ? ch.title : (ch.translations?.[language]?.title || ch.title);
    
    const mdContent = `# ${title}\n\n${text}\n\n---\n*Export generated by EbookForge*`;
    const paddedIndex = (index + 1).toString().padStart(2, '0');
    const safeTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    
    contentFolder?.file(`${paddedIndex}_${safeTitle}.md`, mdContent);
  }));

  const content = await zip.generateAsync({ type: "blob" });
  const downloadUrl = URL.createObjectURL(content);
  const link = document.createElement('a');
  link.href = downloadUrl;
  link.download = `${project.title.replace(/\s+/g, '_')}_Archive.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(downloadUrl);
}

export async function exportToEpub(project: Project, chapters: Chapter[], language: string, publishOptions: any = {}) {
  const epubChapters: { title: string, content: string }[] = [];
  
  for (const ch of chapters) {
    const url = language === 'en' ? ch.contentUrl : ch.translations?.[language]?.contentUrl;
    if (!url) continue;
    
    const response = await fetch(url);
    if (!response.ok) continue;
    const markdownText = await response.text();
    const htmlContent = md.render(markdownText);
    
    const title = language === 'en' ? ch.title : (ch.translations?.[language]?.title || ch.title);
    
    epubChapters.push({
      title,
      content: htmlContent
    });
  }

  const options = {
    title: project.title,
    author: "EbookForge User",
    publisher: "EbookForge",
    description: project.niche,
    cover: project.coverUrl || "", // Use cover image if available
    tocTitle: "Table of Contents",
  };

  const epubFile = await Epub(options, epubChapters);
  
  // Download
  const blob = new Blob([epubFile], { type: 'application/epub+zip' });
  const downloadUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = downloadUrl;
  link.download = `${project.title.replace(/\s+/g, '_')}.epub`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(downloadUrl);
}

export async function exportToPdf(project: Project, chapters: Chapter[], language: string, publishOptions: any = {}) {
  // A simple PDF generation strategy: create a hidden DOM element, render markdown, and use html2canvas + jspdf
  // For standard page format:
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: publishOptions.pageSize || 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 40;
  const maxLineWidth = pageWidth - margin * 2;
  
  // Custom simple rendering for PDF text given jspdf constraints
  let yPos = margin;
  
  // Title page
  pdf.setFontSize(24);
  pdf.text(project.title, pageWidth / 2, yPos + 100, { align: 'center', maxWidth: maxLineWidth });
  pdf.setFontSize(14);
  pdf.text(`Niche: ${project.niche}`, pageWidth / 2, yPos + 140, { align: 'center', maxWidth: maxLineWidth });
  
  if (publishOptions.includeCover && project.coverUrl) {
     try {
         // Attempt to add cover (requires base64 or valid Image obj within CORS)
         const img = new Image();
         img.crossOrigin = "Anonymous";
         img.src = project.coverUrl;
         await new Promise((resolve) => { img.onload = resolve; img.onerror = resolve; });
         pdf.addImage(img, 'JPEG', margin, yPos + 200, pageWidth - margin*2, (pageWidth - margin*2));
     } catch (e) {
         console.warn("Cover image could not be added to PDF", e);
     }
  }

  // Chapters
  pdf.setFontSize(12);
  
  for (const ch of chapters) {
    pdf.addPage();
    yPos = margin;
    
    const title = language === 'en' ? ch.title : (ch.translations?.[language]?.title || ch.title);
    pdf.setFontSize(18);
    pdf.text(title, margin, yPos);
    yPos += 30;
    
    const url = language === 'en' ? ch.contentUrl : ch.translations?.[language]?.contentUrl;
    if (!url) continue;
    
    const response = await fetch(url);
    if (!response.ok) continue;
    const text = await response.text();
    
    // Minimal standard text breaking (simplified for rapid PDF)
    pdf.setFontSize(11);
    const lines = pdf.splitTextToSize(text.replace(/#/g, ''), maxLineWidth);
    
    for (let i = 0; i < lines.length; i++) {
        if (yPos > pageHeight - margin) {
            pdf.addPage();
            yPos = margin;
        }
        pdf.text(lines[i], margin, yPos);
        yPos += 14; 
    }
  }

  pdf.save(`${project.title.replace(/\s+/g, '_')}.pdf`);
}
